version: '3'
services:
    nginx:
        image: nginx:1.23.4-alpine
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - nginx-instance-1
            - nginx-instance-2
            - nginx-instance-3
        networks:
            - nginx-network
    nginx-instance-1:
        image: nginx:1.23.4-alpine
        volumes:
            - ./html/instance-1:/usr/share/nginx/html
        networks:
            - nginx-network
    nginx-instance-2:
        image: nginx:1.23.4-alpine
        volumes:
            - ./html/instance-2:/usr/share/nginx/html
        networks:
            - nginx-network
    nginx-instance-3:
        image: nginx:1.23.4-alpine
        volumes:
            - ./html/instance-3:/usr/share/nginx/html
        networks:
            - nginx-network

# gunakan network biar bisa akses ke container lain
networks:
    nginx-network:
