version: '3'
services:
    nginx-load-balancer:
        build:
            # context directory Dockerfile berada
            context: .
            dockerfile: Dockerfile-load-balancer
        ports:
            - '80:80'
        depends_on:
            - nginx-instance-1
            - nginx-instance-2
            - nginx-instance-3
        networks:
            - nginx-network
    nginx-instance-1:
        build:
            context: .
            dockerfile: Dockerfile-instances
        networks:
            - nginx-network
    nginx-instance-2:
        build:
            context: .
            dockerfile: Dockerfile-instances
        networks:
            - nginx-network
    nginx-instance-3:
        build:
            context: .
            dockerfile: Dockerfile-instances
        networks:
            - nginx-network

# gunakan network biar bisa akses ke container lain
networks:
    nginx-network:
